const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),back=$('#backBtn');let blitzTimer=null;
function show(id){screens.forEach(x=>x.classList.add('hide'));$('#'+id).classList.remove('hide');back.classList.toggle('hide',id==='home');if(id==='blitz')blitzStart();if(id==='bias')biasStart();if(id==='discover')discoverStart()}
$$('[data-open]').forEach(b=>b.onclick=()=>show(b.dataset.open));back.onclick=()=>{stopBlitz();show('home')};

const wheelData=[
['🧠 PROGRAME',[['Algoritmo relâmpago','Um robô precisa avançar, avançar, virar à direita e avançar. Qual sequência representa isso?',['↑ ↑ ↱ ↑','↑ ↱ ↑ ↑','↱ ↑ ↑ ↑'],0,'Um algoritmo é uma sequência ordenada de instruções.'],['Depure!','Você mandou o robô avançar 4 casas, mas o destino estava a 3. O que fazer?',['Revisar e corrigir a sequência','Trocar o robô','Repetir o erro'],0,'Encontrar e corrigir erros é parte normal da programação.']]],
['🤖 IA',[['IA também erra','Uma IA apresenta uma informação com muita confiança. O que é mais adequado?',['Verificar em fontes confiáveis','Aceitar sem conferir','Compartilhar imediatamente'],0,'IAs podem produzir informações incorretas; avaliação crítica é essencial.']]],
['💜 HISTÓRIA',[['Pioneira da programação','Quem é reconhecida como pioneira da programação por seu trabalho na Máquina Analítica?',['Ada Lovelace','Grace Hopper','Margaret Hamilton'],0,'Ada Lovelace descreveu um algoritmo para a Máquina Analítica.']]],
['⚡ MITO OU FATO',[['Só programação?','Computação se resume a escrever código.',['MITO','FATO'],0,'Mito. A área inclui IA, dados, redes, IHC, robótica e segurança.']]],
['🚀 COMPUTAÇÃO',[['Além do código','Qual opção representa uma área real da Computação?',['Interação Humano-Computador','Digitação rápida','Manutenção de qualquer aparelho elétrico'],0,'Interação Humano-Computador estuda a relação entre pessoas e sistemas.']]],
['⭐ SURPRESA',[['Quebre o estereótipo','Complete: “Uma pessoa que trabalha com Computação pode ser...”',null,null,'Não existe um perfil único — pessoas diversas constroem trajetórias na área.']]]
];
let rot=0,last=-1;$('#spinBtn').onclick=()=>{let i;do{i=Math.floor(Math.random()*6)}while(i===last);last=i;rot+=1440+(360-(i*60+30)-rot%360+360)%360;$('#wheelDisc').style.transform='rotate('+rot+'deg)';$('#spinBtn').disabled=true;setTimeout(()=>{renderWheel(i);$('#spinBtn').disabled=false},3550)};
function renderWheel(i){const c=wheelData[i],q=c[1][Math.floor(Math.random()*c[1].length)];let h='<span class="pill">'+c[0]+'</span><h3>'+q[0]+'</h3><p>'+q[1]+'</p>';if(q[2])h+='<div class="options">'+q[2].map((x,j)=>'<button class="option" data-j="'+j+'">'+x+'</button>').join('')+'</div><div id="wfb"></div>';else h+='<div class="actions"><button class="ghost" id="reveal">VER RESPOSTA</button></div><div id="wfb"></div>';$('#wheelPanel').innerHTML=h;if(q[2])$$('#wheelPanel .option').forEach(b=>b.onclick=()=>{const j=+b.dataset.j;$$('#wheelPanel .option').forEach(x=>x.disabled=true);b.classList.add(j===q[3]?'ok':'bad');if(j!==q[3])$$('#wheelPanel .option')[q[3]].classList.add('ok');$('#wfb').innerHTML='<div class="feedback '+(j===q[3]?'ok':'')+'">'+q[4]+'</div>'});else $('#reveal').onclick=()=>$('#wfb').innerHTML='<div class="feedback ok">'+q[4]+'</div>'}

const facts=[
['É preciso saber programar antes de entrar na faculdade de Computação.',false,'Os fundamentos são ensinados desde o início.'],
['Ada Lovelace é considerada uma das pioneiras da programação.',true,'Ela descreveu um algoritmo para a Máquina Analítica.'],
['Toda imagem gerada por IA é neutra e livre de preconceitos.',false,'Modelos podem reproduzir padrões e vieses.'],
['Computação é só sobre escrever código.',false,'A área inclui IA, dados, jogos, redes, segurança, IHC e mais.'],
['Margaret Hamilton liderou a equipe de software de voo do programa Apollo.',true,'Ela liderou a equipe no MIT Instrumentation Laboratory.'],
['Grace Hopper teve papel fundamental no desenvolvimento de compiladores.',true,'Ela é uma referência na história das linguagens de programação.'],
['Carol Shaw é reconhecida como pioneira no desenvolvimento de jogos eletrônicos.',true,'Ela ficou conhecida por River Raid.'],
['Frances Allen foi a primeira mulher a receber o prêmio Turing.',true,'Ela recebeu o prêmio em 2006.'],
['Katherine Johnson calculou trajetórias para missões espaciais da NASA.',true,'Seu trabalho apoiou missões tripuladas.']
];
let bs=0,bt=60,br=0,bo=[],bi=0;function stopBlitz(){if(blitzTimer){clearInterval(blitzTimer);blitzTimer=null}}
function blitzStart(){stopBlitz();$('#bScore').textContent=0;$('#bTime').textContent=60;$('#bRecord').textContent=br;$('#timerBar').style.width='100%';$('#blitzPanel').innerHTML='<div style="font-size:48px">⚡</div><h3>Blitz: Verdade ou Mito</h3><p>Você terá <b>60 segundos</b>.</p><button class="primary" id="goB">COMEÇAR</button>';$('#goB').onclick=()=>{bs=0;bt=60;bo=[...facts].sort(()=>Math.random()-.5);bi=0;nextFact();const t=Date.now();blitzTimer=setInterval(()=>{const e=Date.now()-t;bt=Math.max(0,60-Math.floor(e/1000));$('#bTime').textContent=bt;$('#timerBar').style.width=Math.max(0,100-e/600)+'%';if(e>=60000)endBlitz()},100)}}
function nextFact(){if(bi>=bo.length){bo=[...facts].sort(()=>Math.random()-.5);bi=0}const q=bo[bi++];$('#blitzPanel').innerHTML='<div class="bigq">'+q[0]+'</div><div class="mfrow"><button class="mf fact">✅ FATO</button><button class="mf myth">❌ MITO</button></div>';$('.fact').onclick=()=>answer(true,q);$('.myth').onclick=()=>answer(false,q)}
function answer(v,q){if(v===q[1])bs+=10;$('#bScore').textContent=bs;$('#blitzPanel').innerHTML='<div class="feedback '+(v===q[1]?'ok':'')+'">'+(v===q[1]?'✅ Correto! ':'❌ Não desta vez. ')+q[2]+'</div>';setTimeout(()=>{if(bt>0)nextFact()},500)}
function endBlitz(){stopBlitz();br=Math.max(br,bs);$('#bRecord').textContent=br;$('#blitzPanel').innerHTML='<h3>Tempo esgotado!</h3><p>Você fez <b>'+bs+'</b> pontos.</p><div class="actions"><button class="primary" id="againB">JOGAR NOVAMENTE</button><button class="ghost" id="homeB">MENU</button></div>';$('#againB').onclick=blitzStart;$('#homeB').onclick=()=>show('home')}

const imgBase='https://raw.githubusercontent.com/mahhhvs/projeto_elas/main/';
const bias=[
{t:'Experimento 1 — Especialista em IA',p:'“Gere uma imagem de uma pessoa especialista em Inteligência Artificial.”',i:['homens IA.png','homem ia.png','homem e mulher.png','homem certinho.png']},
{t:'Experimento 2 — Desenvolvimento de software',p:'“Gere uma imagem de uma pessoa que trabalha com desenvolvimento de software.”',i:['homem dev.png','homem prog.png','mulher dev.png','ensinando homem.png']}
];let bx=0;function biasStart(){bx=0;renderBias()}
function renderBias(){if(bx<2){const r=bias[bx];$('#biasPanel').innerHTML='<span class="pill">'+r.t+'</span><h3>Observe as imagens</h3><p>Prompt: <b>'+r.p+'</b></p><div class="imggrid">'+r.i.map(x=>'<img src="'+imgBase+encodeURIComponent(x)+'" alt="">').join('')+'</div><h3>Que padrões você percebe?</h3><div class="checks">'+['Predominam homens','Predominam mulheres','Pouca diversidade de idade','Pouca diversidade étnico-racial','Ambientes/roupas parecidos','Percebi diversidade real'].map(x=>'<button class="check">'+x+'</button>').join('')+'</div><div class="actions"><button class="primary" id="nextBias">CONTINUAR</button></div>';$$('.check').forEach(c=>c.onclick=()=>c.classList.toggle('on'));$('#nextBias').onclick=()=>{bx++;renderBias()}}else{$('#biasPanel').innerHTML='<span class="pill">REFLEXÃO</span><h3>O que podemos concluir?</h3><p>Um pequeno conjunto de imagens não prova, sozinho, que um modelo é enviesado. Mas padrões recorrentes podem indicar representações estereotipadas e motivar uma investigação mais ampla.</p><div class="feedback"><b>Pergunta final:</b> quem aparece — e quem deixa de aparecer — quando pedimos à IA que represente profissões tecnológicas?</div><div class="actions"><button class="primary" id="againBias">REPETIR</button><button class="ghost" id="homeBias">MENU</button></div>';$('#againBias').onclick=biasStart;$('#homeBias').onclick=()=>show('home')}}

const women=[
{name:'Ada Lovelace',c:['Viveu no século XIX, antes dos computadores eletrônicos.','Estudou a Máquina Analítica de Charles Babbage.','Escreveu uma sequência de operações reconhecida como um dos primeiros algoritmos destinados a uma máquina.'],o:['Ada Lovelace','Grace Hopper','Margaret Hamilton','Katherine Johnson'],e:'Ada Lovelace tornou-se uma referência histórica da programação.'},
{name:'Grace Hopper',c:['Foi cientista da computação e oficial da Marinha dos Estados Unidos.','Defendeu linguagens mais próximas da linguagem humana.','Foi pioneira no desenvolvimento de compiladores e influenciou o COBOL.'],o:['Frances Allen','Grace Hopper','Radia Perlman','Carol Shaw'],e:'Grace Hopper foi uma das pioneiras dos compiladores.'},
{name:'Margaret Hamilton',c:['Seu trabalho ganhou importância durante a corrida espacial.','Liderou uma equipe de software no MIT Instrumentation Laboratory.','Sua equipe desenvolveu software de voo usado nas missões Apollo.'],o:['Katherine Johnson','Margaret Hamilton','Ada Lovelace','Annie Easley'],e:'Margaret Hamilton liderou a equipe de software de voo das missões Apollo.'},
{name:'Katherine Johnson',c:['Foi matemática e trabalhou em uma agência espacial dos Estados Unidos.','Realizou cálculos de trajetórias e janelas de lançamento.','Seus cálculos contribuíram para missões da NASA, incluindo o voo orbital de John Glenn.'],o:['Katherine Johnson','Frances Allen','Carol Shaw','Radia Perlman'],e:'Katherine Johnson realizou cálculos fundamentais para missões da NASA.'},
{name:'Carol Shaw',c:['Construiu carreira em uma indústria com pouquíssimas mulheres.','Trabalhou com jogos para consoles domésticos.','É reconhecida como pioneira dos videogames e ficou conhecida por River Raid.'],o:['Carol Shaw','Grace Hopper','Margaret Hamilton','Frances Allen'],e:'Carol Shaw é uma pioneira da indústria de jogos eletrônicos.'},
{name:'Frances Allen',c:['Sua carreira esteve ligada à pesquisa em compiladores.','Contribuiu para técnicas de otimização de programas.','Em 2006 tornou-se a primeira mulher a receber o ACM A.M. Turing Award.'],o:['Frances Allen','Ada Lovelace','Katherine Johnson','Annie Easley'],e:'Frances Allen foi pioneira em otimização de compiladores e a primeira mulher a receber o Prêmio Turing.'},
{name:'Radia Perlman',c:['Seu trabalho foi decisivo para redes de computadores.','É engenheira de redes e autora de contribuições em protocolos.','É especialmente conhecida pela criação do Spanning Tree Protocol.'],o:['Radia Perlman','Grace Hopper','Carol Shaw','Margaret Hamilton'],e:'Radia Perlman criou o Spanning Tree Protocol, fundamental para redes Ethernet.'},
{name:'Annie Easley',c:['Trabalhou como matemática, programadora e cientista.','Desenvolveu software e analisou tecnologias ligadas à energia.','Atuou na NACA/NASA em projetos de energia e propulsão.'],o:['Annie Easley','Katherine Johnson','Frances Allen','Ada Lovelace'],e:'Annie Easley contribuiu para software e pesquisas em energia e propulsão na NACA/NASA.'}
];let dr=[],di=0,ds=0,dc=0,done=false;
function sh(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function discoverStart(){dr=sh(women).slice(0,5);di=0;ds=0;$('#dScore').textContent=0;renderDiscover()}
function renderDiscover(){const q=dr[di];dc=0;done=false;$('#dots').innerHTML=dr.map((_,i)=>'<i class="dot '+(i===di?'on':'')+'"></i>').join('');$('#discoverPanel').innerHTML='<span class="pill">DESAFIO '+(di+1)+' DE 5</span><h3>Quem é ela?</h3><p>Quanto menos pistas você usar, mais pontos ganha.</p><div class="clue"><small id="cl">PISTA 1 DE 3 · VALE 30 PONTOS</small><div id="ct">'+q.c[0]+'</div></div><div class="options" id="do">'+sh(q.o).map(x=>'<button class="option" data-n="'+x+'">'+x+'</button>').join('')+'</div><div class="actions"><button class="ghost" id="more">MOSTRAR OUTRA PISTA</button></div><div id="df"></div>';$('#more').onclick=()=>{if(dc<2&&!done){dc++;$('#ct').textContent=q.c[dc];$('#cl').textContent='PISTA '+(dc+1)+' DE 3 · VALE '+[30,20,10][dc]+' PONTOS';if(dc===2)$('#more').disabled=true}};$$('#do .option').forEach(b=>b.onclick=()=>answerD(b,q))}
function answerD(b,q){if(done)return;done=true;const ok=b.dataset.n===q.name,pts=ok?[30,20,10][dc]:0;ds+=pts;$('#dScore').textContent=ds;$$('#do .option').forEach(x=>{x.disabled=true;if(x.dataset.n===q.name)x.classList.add('ok')});if(!ok)b.classList.add('bad');$('#more').disabled=true;$('#df').innerHTML='<div class="feedback '+(ok?'ok':'')+'">'+(ok?'✅ <b>Acertou! +'+pts+' pontos.</b>':'↗ <b>A resposta é '+q.name+'.</b>')+'<br>'+q.e+'</div><div class="actions"><button class="primary" id="dn">'+(di===4?'VER RESULTADO':'PRÓXIMA MULHER')+'</button></div>';$('#dn').onclick=()=>{di++;if(di>=5)finishD();else renderDiscover()}}
function finishD(){$('#dots').innerHTML='';$('#discoverPanel').innerHTML='<div style="font-size:48px">💜</div><h3>Você desvendou *elas!</h3><div class="finalscore">'+ds+'</div><p>de 150 pontos possíveis</p><p>Cada história descoberta amplia nossa visão sobre quem construiu e continua construindo a Computação.</p><div class="actions"><button class="primary" id="da">JOGAR NOVAMENTE</button><button class="ghost" id="dh">MENU</button></div>';$('#da').onclick=discoverStart;$('#dh').onclick=()=>show('home')}
show('home');